from collections import deque
q = deque() 
q.append("A")
q.append("B")
q.append("C")
q.append("D")
q.append("E")
print("Initial Queue : ", q)
print("Poped elements from the Queue : ")
print(q.popleft())
print(q.popleft())
print(q.popleft())
print("Queue After Deleting the elements from the Queue : ", end = " ")
print(q)