Queue = []
Queue.append(10)
Queue.append(20)
Queue.append(30)
Queue.append(40)
Queue.append(50)
print("this is the Initial Queue : ", Queue)
print("This is the Size of the Given Queue : ",len(Queue))
print(Queue.pop())
print(Queue.pop())
print("Queue After Deletion : ", Queue)