from queue import LifoQueue 
stack = LifoQueue(maxsize = 5)
print("initial size of the stack is : ",stack.qsize())
print("Empty : ",stack.empty())
stack.put(1)
stack.put(3)
stack.put(5)
stack.put(7)
stack.put(9)
print("is stack  Full : ", stack.full())
print("is stack Empty : ",stack.empty())
print("Removed element : ",stack.get())
print("Removed elment  : ",stack.get())
print("Removed element : ",stack.get())
print("Removed element :",stack.get())
print("Is stack Full : ",stack.full())
print("Removed element :",stack.get())
print("is stack  Empty : ",stack.empty())
